"""Package the generated lake artwork as a bounded, embedded PNG resource."""
from pathlib import Path
import io
from PIL import Image

root = Path(__file__).resolve().parents[1]
buffer = io.BytesIO()
with Image.open(root / "design/lake-background.png") as image:
    image.convert("RGB").resize((1280, 720), Image.Resampling.LANCZOS).save(buffer, "PNG", optimize=True)
data = buffer.getvalue()
lines = ["/* Generated by scripts/embed_ui_background.py. */", "static const unsigned char lake_png[] = {"]
lines += [",".join(map(str, data[i:i+128])) + "," for i in range(0, len(data), 128)]
lines += ["};", ""]
(root / "src/ui/ui_lake_data.h").write_text("\n".join(lines), encoding="ascii", newline="\n")
