"""Bake licensed DejaVu Sans into a compact antialiased font for the native UI.

Usage: python generate_ui_font.py FONT_DIRECTORY OUTPUT_HEADER
No font library or file I/O is needed on the console.
"""
from pathlib import Path
import sys
from PIL import Image, ImageDraw, ImageFont

root, output = map(Path, sys.argv[1:])
pixels, glyphs = [], []
for filename in ("DejaVuSans.ttf", "DejaVuSans-Bold.ttf"):
    font = ImageFont.truetype(str(root / filename), 48)
    for code in range(32, 127):
        advance = round(font.getlength(chr(code)))
        width = advance + 3
        image = Image.new("L", (width, 64))
        ImageDraw.Draw(image).text((1, 0), chr(code), font=font, fill=255)
        glyphs.append((len(pixels), width, advance))
        pixels.extend(image.tobytes())
lines = ["/* Generated by scripts/generate_ui_font.py. See vendor/FONT-LICENSE.txt. */",
         "static const struct { unsigned offset; unsigned short width, advance; } sans_glyphs[] = {"]
lines += [f"{{{offset},{width},{advance}}}," for offset, width, advance in glyphs]
lines += ["};", "static const unsigned char sans_pixels[] = {"]
lines += [",".join(map(str, pixels[i:i+128])) + "," for i in range(0, len(pixels), 128)]
lines += ["};", ""]
output.write_text("\n".join(lines), encoding="ascii", newline="\n")
